# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'science.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from math import sqrt
from random import triangular

class Attvud(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Mass_box = QtWidgets.QLineEdit(self.centralwidget)
        self.Mass_box.setGeometry(QtCore.QRect(600, 120, 113, 22))
        self.Mass_box.setObjectName("Mass_box")

        self.Mass_label = QtWidgets.QLabel(self.centralwidget)
        self.Mass_label.setGeometry(QtCore.QRect(720, 120, 55, 16))
        self.Mass_label.setObjectName("Mass_label")

        self.Extra_Mass_label = QtWidgets.QLabel(self.centralwidget)
        self.Extra_Mass_label.setGeometry(QtCore.QRect(720, 160, 55, 16))
        self.Extra_Mass_label.setObjectName("Extra_Mass_label")

        self.Lenght_a_label = QtWidgets.QLabel(self.centralwidget)
        self.Lenght_a_label.setGeometry(QtCore.QRect(720, 215, 55, 16))
        self.Lenght_a_label.setObjectName("Lenght_a_label")

        self.Lenght_label = QtWidgets.QLabel(self.centralwidget)
        self.Lenght_label.setGeometry(QtCore.QRect(720, 255, 55, 16))
        self.Lenght_label.setObjectName("Lenght_label")

        self.Mass = QtWidgets.QLabel(self.centralwidget)
        self.Mass.setGeometry(QtCore.QRect(350, 120, 111, 20))
        self.Mass.setObjectName("Mass")


        self.Title_input = QtWidgets.QLabel(self.centralwidget)
        self.Title_input.setGeometry(QtCore.QRect(350, 60, 500, 20))
        self.Title_input.setObjectName("Title_input")

        self.Extra_Mass = QtWidgets.QLabel(self.centralwidget)
        self.Extra_Mass.setGeometry(QtCore.QRect(350, 160, 131, 20))
        self.Extra_Mass.setObjectName("Extra_Mass")

        self.Lenght_a = QtWidgets.QLabel(self.centralwidget)
        self.Lenght_a.setGeometry(QtCore.QRect(350, 190, 261, 51))
        self.Lenght_a.setWordWrap(False)
        self.Lenght_a.setObjectName("Lenght_a")

        self.Length = QtWidgets.QLabel(self.centralwidget)
        self.Length.setGeometry(QtCore.QRect(350, 230, 261, 51))
        self.Length.setWordWrap(False)
        self.Length.setObjectName("Length")

        self.Time = QtWidgets.QLabel(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(350, 330, 211, 51))
        self.Time.setWordWrap(False)
        self.Time.setObjectName("Time")

        self.Time_result = QtWidgets.QLabel(self.centralwidget)
        self.Time_result.setGeometry(QtCore.QRect(570, 345, 240, 21))
        self.Time_result.setWordWrap(False)
        self.Time_result.setObjectName("Time_result")

        self.Extra_mass_box = QtWidgets.QLineEdit(self.centralwidget)
        self.Extra_mass_box.setGeometry(QtCore.QRect(600, 160, 113, 22))
        self.Extra_mass_box.setObjectName("Extra_mass_box")

        self.Lenght_a_box = QtWidgets.QLineEdit(self.centralwidget)
        self.Lenght_a_box.setGeometry(QtCore.QRect(600, 215, 113, 22))
        self.Lenght_a_box.setObjectName("Lenght_a_box")

        self.Lenght_box = QtWidgets.QLineEdit(self.centralwidget)
        self.Lenght_box.setGeometry(QtCore.QRect(600, 255, 113, 22))
        self.Lenght_box.setObjectName("Lenght_box")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(660, 530, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.result)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Прибор Атвуда"))
        self.Mass.setText(_translate("MainWindow", "Масса грузов М:"))
        self.Extra_Mass.setText(_translate("MainWindow", "Масса перегруза m:"))
        self.Lenght_a.setText(_translate("MainWindow", "Длина пути равноускоренного\nдвижения:"))
        self.Length.setText(_translate("MainWindow", "Длина пути равномерного\nдвижения:"))
        self.Time.setText(_translate("MainWindow", "Время равномерного движения:"))
        self.Time_result.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
        self.Mass_label.setText(_translate("MainWindow", "кг"))
        self.Extra_Mass_label.setText(_translate("MainWindow", "кг"))
        self.Lenght_a_label.setText(_translate("MainWindow", "м"))
        self.Lenght_label.setText(_translate("MainWindow", "м"))
        self.Title_input.setText(_translate('MainWindow', "Исходные данные. Ввод десятичных значений через точку!"))

    def result(self):
        try:
            L = self.Lenght_box.text()
            l = self.Lenght_a_box.text()
            M = self.Mass_box.text()
            m = self.Extra_mass_box.text()
            g = 9.81
            t = sqrt(((float(L) ** 2) * (2 * float(M) + float(m))) / (g * float(m) * 2 * float(l)))
            randt = str(round(triangular(t * 0.95, t * 1.05), 3))+ ' c.'
            self.Time_result.setText(randt)
        except Exception:
            self.Time_result.setText('Значения введены неверно!')
if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Attvud()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
